### ISSUE TITLE
GearSwap - pet_aftercast not always triggering

### ISSUE THREAD

**Issue by svanheulen** [Byrth/Lua#357]
Sorry, I should have reported this when I first noticed it, but I think it was around version 0.896 that the pet_aftercast event stopped working all of the time. Sometimes it triggers, sometimes it doesn't... the most annoying kind of bug to troubleshoot :(

**Comment by Byrth** [comment]
I have adjusted this so it should be more reliable now (on -dev). The standard delay for avatar BPs is something like 3.7 seconds and I set the time-out delay at 4 seconds, so depending on packet frequency sometimes it was getting cleared out of the registry before it landed.
